name: Frontend Build

on:
  push:
    branches:
      - main  # Adjust this branch name to your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Move Build Files
        run: mv frontend/build ./frontend-build

      - name: Commit and Push Build Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add frontend-build
          git commit -m "Add frontend build files"
          git push
